apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - deployment.yaml
configMapGenerator:
  - name: deployment-env
    namespace: simple-go-ns
    literals:
      - ENV=staging
